#!/bin/bash

user="Meysam Khodaei"
os='Manjaro'
kernel="$(uname -sr)"
init="systemd"
uptime="$(uptime -p | sed 's/up //')"  
packages="$(pacman -Qq | wc -l)"
shell="$(basename ${SHELL})"
WM=i3
terminal=URxvt
memory="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"


bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

lc="${reset}${bold}${green}"
nc="${reset}${bold}${green}"
ic="${reset}"
c0="${reset}${bold}${red}"
c1="${reset}${green}"

cat <<EOF
${c0}      ___     
${c0}     /\  \    	${lc}USER:         ${ic}${user}${reset}
${c0}    |::\  \   	${lc}OS:           ${ic}${os}${reset}
${c0}    |:|:\  \  	${lc}KERNEL:       ${ic}${kernel}${reset}
${c0}  __|:|\:\  \ 	${lc}INIT:         ${ic}${init}${reset}
${c0} /::::|_\:\__\	${lc}UPTIME:       ${ic}${uptime}${reset}
${c0} \:\~~\  \/__/	${lc}PACKAGES:     ${ic}${packages}${reset}
${c0}  \:\  \      	${lc}SHELL:        ${ic}${shell}${reset}
${c0}   \:\  \     	${lc}WM:           ${ic}${WM}${reset}
${c0}    \:\__\    	${lc}TERMINAL:     ${ic}${terminal}${reset}
${c0}     \/__/    	${lc}MEMORY :      ${ic}${memory}${resst}

EOF
